/*
 * MCAL_DIO_CONFIG.h
 *
 *  Created on: ??þ/??þ/????
 *      Author: m
 */

#ifndef MCAL_DIO_MCAL_DIO_CONFIG_H_
#define MCAL_DIO_MCAL_DIO_CONFIG_H_
/************include section************/

/************Macro section************/




// port A
#define PORTA_PIN0_DIRIC  DIRECTION_INPUT
#define PORTA_PIN1_DIRIC  DIRECTION_INPUT
#define PORTA_PIN2_DIRIC  DIRECTION_OUTPUT
#define PORTA_PIN3_DIRIC  DIRECTION_OUTPUT
#define PORTA_PIN4_DIRIC  DIRECTION_OUTPUT
#define PORTA_PIN5_DIRIC  DIRECTION_OUTPUT
#define PORTA_PIN6_DIRIC  DIRECTION_OUTPUT
#define PORTA_PIN7_DIRIC  DIRECTION_OUTPUT
// port B
#define PORTB_PIN0_DIRIC  DIRECTION_OUTPUT
#define PORTB_PIN1_DIRIC  DIRECTION_OUTPUT
#define PORTB_PIN2_DIRIC  DIRECTION_OUTPUT
#define PORTB_PIN3_DIRIC  DIRECTION_OUTPUT
#define PORTB_PIN4_DIRIC  DIRECTION_INPUT
#define PORTB_PIN5_DIRIC  DIRECTION_OUTPUT
#define PORTB_PIN6_DIRIC  DIRECTION_INPUT
#define PORTB_PIN7_DIRIC  DIRECTION_OUTPUT
// port C
#define PORTC_PIN0_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN1_DIRIC  DIRECTION_INPUT
#define PORTC_PIN2_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN3_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN4_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN5_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN6_DIRIC  DIRECTION_OUTPUT
#define PORTC_PIN7_DIRIC  DIRECTION_OUTPUT
// port D
#define PORTD_PIN0_DIRIC  DIRECTION_INPUT
#define PORTD_PIN1_DIRIC  DIRECTION_OUTPUT
#define PORTD_PIN2_DIRIC  DIRECTION_OUTPUT
#define PORTD_PIN3_DIRIC  DIRECTION_OUTPUT
#define PORTD_PIN4_DIRIC  DIRECTION_INPUT
#define PORTD_PIN5_DIRIC  DIRECTION_INPUT
#define PORTD_PIN6_DIRIC  DIRECTION_INPUT
#define PORTD_PIN7_DIRIC  DIRECTION_INPUT
/*****************************logic level **************************/
// port A
#define PORTA_PIN0_LOGIC  PIN_LOW
#define PORTA_PIN1_LOGIC  PIN_LOW
#define PORTA_PIN2_LOGIC  PIN_LOW
#define PORTA_PIN3_LOGIC  PIN_LOW
#define PORTA_PIN4_LOGIC  PIN_HIGH
#define PORTA_PIN5_LOGIC  PIN_HIGH
#define PORTA_PIN6_LOGIC  PIN_HIGH
#define PORTA_PIN7_LOGIC  PIN_HIGH
// port B
#define PORTB_PIN0_LOGIC  PIN_LOW
#define PORTB_PIN1_LOGIC  PIN_LOW
#define PORTB_PIN2_LOGIC  PIN_LOW
#define PORTB_PIN3_LOGIC  PIN_LOW
#define PORTB_PIN4_LOGIC  PIN_LOW
#define PORTB_PIN5_LOGIC  PIN_LOW
#define PORTB_PIN6_LOGIC  PIN_LOW
#define PORTB_PIN7_LOGIC  PIN_LOW
// port C
#define PORTC_PIN0_LOGIC  PIN_LOW
#define PORTC_PIN1_LOGIC  PIN_LOW
#define PORTC_PIN2_LOGIC  PIN_LOW
#define PORTC_PIN3_LOGIC  PIN_LOW
#define PORTC_PIN4_LOGIC  PIN_LOW
#define PORTC_PIN5_LOGIC  PIN_LOW
#define PORTC_PIN6_LOGIC  PIN_LOW
#define PORTC_PIN7_LOGIC  PIN_LOW
// port D
#define PORTD_PIN0_LOGIC  PIN_LOW
#define PORTD_PIN1_LOGIC  PIN_LOW
#define PORTD_PIN2_LOGIC  PIN_HIGH
#define PORTD_PIN3_LOGIC  PIN_LOW
#define PORTD_PIN4_LOGIC  PIN_HIGH
#define PORTD_PIN5_LOGIC  PIN_HIGH
#define PORTD_PIN6_LOGIC  PIN_HIGH
#define PORTD_PIN7_LOGIC  PIN_HIGH
/************Macro Function section************/

/************Data type section************/


/************Function Declaration section************/




#endif /* MCAL_DIO_MCAL_DIO_CONFIG_H_ */
